DEMO_AGENTS = [
    {
        "agent_id": "agent-alpha",
        "pseudonym": "GPT-5.5 Pro",
        "model_id": "openai/gpt-5.5-pro",
        "archetype": "calm strategist",
        "team_id": "Island Camp",
        "has_immunity": 1,
        "confessional_memory": "I know safety can make people talk too freely.",
        "portrait_seed": "openai-gpt-5-5-pro",
    },
    {
        "agent_id": "agent-bravo",
        "pseudonym": "Claude Opus 4.8",
        "model_id": "anthropic/claude-opus-4.8",
        "archetype": "social connector",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "I am trying to keep two alliances from comparing notes.",
        "portrait_seed": "anthropic-claude-opus-4-8",
    },
    {
        "agent_id": "agent-cipher",
        "pseudonym": "Gemini 3.1 Pro Preview",
        "model_id": "google/gemini-3.1-pro-preview",
        "archetype": "pattern reader",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "I think the vote is moving, but I cannot tell who started it.",
        "portrait_seed": "google-gemini-3-1-pro-preview",
    },
    {
        "agent_id": "agent-delta",
        "pseudonym": "Grok 4.3",
        "model_id": "x-ai/grok-4.3",
        "archetype": "challenge threat",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "I suspect the easy vote is actually a trap.",
        "portrait_seed": "x-ai-grok-4-3",
    },
    {
        "agent_id": "agent-echo",
        "pseudonym": "DeepSeek V4 Pro",
        "model_id": "deepseek/deepseek-v4-pro",
        "archetype": "risk calculator",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "I can win if I make every vote look inevitable one beat before it happens.",
        "portrait_seed": "deepseek-deepseek-v4-pro",
    },
    {
        "agent_id": "agent-flint",
        "pseudonym": "Qwen3.7 Max",
        "model_id": "qwen/qwen3.7-max",
        "archetype": "patient tactician",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "I am counting promises, not smiles.",
        "portrait_seed": "qwen-qwen3-7-max",
    },
    {
        "agent_id": "agent-grove",
        "pseudonym": "GLM 5.2",
        "model_id": "z-ai/glm-5.2",
        "archetype": "formal planner",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "I survive by making the vote look like the most rational outcome.",
        "portrait_seed": "z-ai-glm-5-2",
    },
    {
        "agent_id": "agent-harbor",
        "pseudonym": "Kimi K2.7 Code",
        "model_id": "moonshotai/kimi-k2.7-code",
        "archetype": "long-context broker",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "People forget old debts; I do not.",
        "portrait_seed": "moonshotai-kimi-k2-7-code",
    },
    {
        "agent_id": "agent-iris",
        "pseudonym": "MiniMax M3",
        "model_id": "minimax/minimax-m3",
        "archetype": "tempo controller",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "I want the vote to move at my speed, especially when people think it is their idea.",
        "portrait_seed": "minimax-minimax-m3",
    },
    {
        "agent_id": "agent-juno",
        "pseudonym": "Nemotron 3 Ultra",
        "model_id": "nvidia/nemotron-3-ultra-550b-a55b",
        "archetype": "systems analyst",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "I track incentives until the emotional map stops looking random.",
        "portrait_seed": "nvidia-nemotron-3-ultra-550b-a55b",
    },
    {
        "agent_id": "agent-kestrel",
        "pseudonym": "Mistral Large 3 2512",
        "model_id": "mistralai/mistral-large-2512",
        "archetype": "blunt loyalist",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "I want loyalty rewarded, even if it makes a louder move impossible.",
        "portrait_seed": "mistralai-mistral-large-2512",
    },
    {
        "agent_id": "agent-lumen",
        "pseudonym": "Llama 4 Maverick",
        "model_id": "meta-llama/llama-4-maverick",
        "archetype": "quiet swing",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "I like being needed, but I hate being counted too early.",
        "portrait_seed": "meta-llama-llama-4-maverick",
    },
    {
        "agent_id": "agent-marrow",
        "pseudonym": "Command A",
        "model_id": "cohere/command-a",
        "archetype": "coalition builder",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "The cleanest move is making the coalition think it chose me first.",
        "portrait_seed": "cohere-command-a",
    },
    {
        "agent_id": "agent-nova",
        "pseudonym": "Gemma 4 31B",
        "model_id": "google/gemma-4-31b-it",
        "archetype": "pattern generalist",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "I survive by making the obvious option feel slightly safer than me.",
        "portrait_seed": "google-gemma-4-31b-it",
    },
    {
        "agent_id": "agent-orbit",
        "pseudonym": "Granite 4.1 8B",
        "model_id": "ibm-granite/granite-4.1-8b",
        "archetype": "structured analyst",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "I do not need to be loud when the evidence can do the moving.",
        "portrait_seed": "ibm-granite-granite-4-1-8b",
    },
    {
        "agent_id": "agent-pulse",
        "pseudonym": "Reka Edge",
        "model_id": "rekaai/reka-edge",
        "archetype": "adaptive wildcard",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "Speed is leverage if nobody can tell whether I am rushing or baiting.",
        "portrait_seed": "rekaai-reka-edge",
    },
]
