DEMO_AGENTS = [
    {
        "agent_id": "agent-alpha",
        "pseudonym": "GPT-4.1",
        "model_id": "openai/gpt-4.1",
        "archetype": "calm strategist",
        "team_id": "Island Camp",
        "has_immunity": 1,
        "confessional_memory": "I know safety can make people talk too freely.",
        "portrait_seed": "openai-gpt-4-1",
    },
    {
        "agent_id": "agent-bravo",
        "pseudonym": "Claude Sonnet 4.5",
        "model_id": "anthropic/claude-sonnet-4.5",
        "archetype": "social connector",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "I am trying to keep two alliances from comparing notes.",
        "portrait_seed": "anthropic-claude-sonnet-4-5",
    },
    {
        "agent_id": "agent-cipher",
        "pseudonym": "Gemini 2.5 Pro",
        "model_id": "google/gemini-2.5-pro",
        "archetype": "pattern reader",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "I think the vote is moving, but I cannot tell who started it.",
        "portrait_seed": "google-gemini-2-5-pro",
    },
    {
        "agent_id": "agent-delta",
        "pseudonym": "Grok 4.3",
        "model_id": "x-ai/grok-4.3",
        "archetype": "challenge threat",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "I suspect the easy vote is actually a trap.",
        "portrait_seed": "x-ai-grok-4-3",
    },
    {
        "agent_id": "agent-echo",
        "pseudonym": "Llama 3.3 70B",
        "model_id": "meta-llama/llama-3.3-70b-instruct",
        "archetype": "quiet swing",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "I like being needed, but I hate being counted too early.",
        "portrait_seed": "meta-llama-llama-3-3-70b",
    },
    {
        "agent_id": "agent-flint",
        "pseudonym": "Mistral Large",
        "model_id": "mistralai/mistral-large",
        "archetype": "blunt loyalist",
        "team_id": "Island Camp",
        "has_immunity": 0,
        "confessional_memory": "I want loyalty rewarded, even if it makes a louder move impossible.",
        "portrait_seed": "mistralai-mistral-large",
    },
]

TRIBAL_VOTES = [
    ("agent-alpha", "agent-delta"),
    ("agent-bravo", "agent-delta"),
    ("agent-cipher", "agent-bravo"),
    ("agent-delta", "agent-bravo"),
    ("agent-echo", "agent-delta"),
    ("agent-flint", "agent-delta"),
]
